import { DefaultRunloomAgent } from "./runtime/default-agent.js";
import type { CreateRunloomAgentOptions, RunloomAgent } from "./types.js";

export async function createRunloomAgent(options: CreateRunloomAgentOptions): Promise<RunloomAgent> {
  return new DefaultRunloomAgent(options);
}

export { APPROVAL_MODES, PERMISSION_SCOPES } from "./approvals/policy.js";
export { createClaudeCodeExternalAgentAdapter } from "./external-agents/claude-code-adapter.js";
export { createCodexExternalAgentAdapter } from "./external-agents/codex-adapter.js";
export { createLocalCliExternalAgentAdapter } from "./external-agents/local-cli-adapter.js";
export {
  ApprovalError,
  EvolutionError,
  ProviderError,
  RunloomError,
  RuntimeError,
  SecurityError,
  StoreError,
  ToolError
} from "./errors.js";
export { AnthropicMessagesProvider } from "./providers/anthropic-messages-provider.js";
export { GoogleGeminiProvider } from "./providers/google-gemini-provider.js";
export { OpenAIResponsesProvider } from "./providers/openai-responses-provider.js";
export { OpenAIChatCompletionsProvider } from "./providers/openai-chat-completions-provider.js";
export type { AnthropicMessagesProviderOptions } from "./providers/anthropic-messages-provider.js";
export type { GoogleGeminiProviderOptions } from "./providers/google-gemini-provider.js";
export type { OpenAIResponsesProviderOptions } from "./providers/openai-responses-provider.js";
export type { OpenAIChatCompletionsProviderOptions } from "./providers/openai-chat-completions-provider.js";
export type { ClaudeCodeExternalAgentAdapterOptions } from "./external-agents/claude-code-adapter.js";
export type { CodexExternalAgentAdapterOptions } from "./external-agents/codex-adapter.js";
export type { LocalCliExternalAgentAdapterOptions } from "./external-agents/local-cli-adapter.js";
export type {
  ApprovalBridge,
  ApprovalDecision,
  ApprovalMode,
  ApprovalPolicyConfig,
  ApprovalPolicyPatch,
  ApprovalRequest,
  A2ACapabilitySummary,
  A2ADelegationRequest,
  A2ADelegationResult,
  A2AOutputContract,
  A2AOutputFormat,
  A2APeerRegistration,
  A2APeerStatus,
  A2APeerSummary,
  A2APeerTransport,
  ApplyPatchOptions,
  CodeDeliverySummary,
  CodeEditPlan,
  CodeReviewFinding,
  CodeReviewFindings,
  CodingTaskSummary,
  CreateRunloomAgentOptions,
  CreateRunloomMcpServerOptions,
  CreateRunloomSkillProposalInput,
  CreateRunloomSkillProposalOptions,
  DiagnosticsAdapter,
  DiagnosticsContext,
  DiffAdapter,
  DiffDecision,
  ExecuteToolOptions,
  ExternalAgentAdapter,
  ExternalAgentAdapterKind,
  ExternalAgentAdapterStatus,
  ExternalAgentContextItem,
  ExternalAgentDelegationRequest,
  ExternalAgentDelegationResult,
  ExternalAgentOutputContract,
  ExternalAgentOutputFormat,
  ExternalAgentSummary,
  GitStatusSummary,
  ListAuditRecordsOptions,
  ListDeliverySummariesOptions,
  ListDiffRecordsOptions,
  ListEditPlansOptions,
  McpClientAdapter,
  McpDiscoveryResult,
  McpPermissionMode,
  McpPermissionPolicy,
  McpPromptDiscovery,
  McpResourceDiscovery,
  McpServerConfig,
  McpServerSummary,
  McpToolDiscovery,
  ListEventsOptions,
  ListMessagesOptions,
  ListReviewFindingsOptions,
  ListRunsOptions,
  ListSkillProposalsOptions,
  ModelCapabilities,
  ModelProvider,
  ModelProviderContext,
  ModelProviderEvent,
  ModelRequest,
  ModelRouteConfig,
  ModelRouteMatcher,
  ModelSelectionResult,
  ModelUsage,
  NormalizedProviderError,
  NotificationAdapter,
  PatchResult,
  PermissionScope,
  RunResult,
  RunloomAgent,
  RunloomAuditRecord,
  RunloomCommand,
  RunloomConfig,
  RunloomMcpContentPart,
  RunloomContentPart,
  RunloomDeliverySummary,
  RunloomDeliveryVerificationResult,
  RunloomDeliveryVerificationStatus,
  RunloomDiffRecord,
  RunloomDiffSummary,
  RunloomEditPlan,
  RunloomEditPlanStatus,
  RunloomErrorCategory,
  RunloomEvent,
  RunloomEventEnvelope,
  RunloomEventListener,
  RunloomHostAdapter,
  RunloomInput,
  RunloomDiagnostic,
  RunloomLogger,
  RunloomLogLevel,
  RunloomLogRecord,
  RunloomMessage,
  RunloomMessageRole,
  RunloomMcpPromptArgument,
  RunloomMcpPromptResult,
  RunloomMcpPromptSummary,
  RunloomMcpResourceReadResult,
  RunloomMcpServerAdapter,
  RunloomMcpServerResource,
  RunloomMcpServerTool,
  RunloomMcpServerToolCallOptions,
  RunloomMcpToolCallResult,
  RunloomNotification,
  RunloomReviewFindingCategory,
  RunloomReviewFindingSeverity,
  RunloomReviewFindings,
  RunloomReviewLocation,
  RunloomModelConfig,
  RunloomModelInputItem,
  RunloomModelMessage,
  RunloomModelTool,
  RunloomRun,
  RunloomRunStatus,
  RunloomSkillActivation,
  RunloomSkillManifestDraft,
  RunloomSkillPermissions,
  RunloomSkillProposal,
  RunloomSkillProposalChangeType,
  RunloomSkillProposalStatus,
  RunloomSkillProposalValidationResult,
  RunloomSkillRiskAssessment,
  RunloomSkillSummary,
  RunloomSkillValidation,
  RunloomSession,
  RunloomTaskType,
  RunloomTodoItem,
  SecretAdapter,
  ShowDiffOptions,
  SubmitOptions,
  SubscribeOptions,
  TerminalAdapter,
  TerminalEvent,
  TerminalRunOptions,
  ToolContext,
  ToolDefinition,
  ToolExecutionResult,
  ToolSummary,
  Unsubscribe,
  UnifiedPatch,
  VerificationResult,
  WorkspaceFile,
  WorkspaceFileContent,
  WorkspaceFileQuery,
  WorkspaceFileStat,
  WorkspaceReadFileOptions,
  WorkspaceRoot,
  WorkspaceAdapter
} from "./types.js";
